I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 188, in script
    show prota normal at center
Exception: Image 'prota' does not accept attributes 'normal'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 188, in script
    show prota normal at center
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Iván\Documents\Iván\Desarrollo de videojuegos\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'prota' does not accept attributes 'normal'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
dokidoki3 1.0
Sat Dec 14 10:38:12 2024
